---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Documentación
- type: document
  path: _data/docs.yml
  label: Menú
- type: directory
  path: _docs
  label: Documentos
  create: all
  match: "**/*"
- type: heading
  label: Resto de la página
- type: jekyll-posts
  label: Posts
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Páginas
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
